fidelity: break up selection and computation
mladenovak/interferopy pull request #19
Opened 2021-08-06 09:27 UTC by lboogaard

2021-08-06 09:28 UTC, lboogaard commented on interferopy/tools.py
> +    ax2.plot(bins, hist_N_fitted, drawstyle='steps-mid')
Are you sure you want to plot `hist_N_fitted` here and not `hist_N`?

2021-09-09 09:33 UTC, rameyer commented on interferopy/tools.py
> +    ax2.plot(bins, hist_N_fitted, drawstyle='steps-mid')
No, you're right it should be hist_N. One could add a line with hist_N fitted as well.

2021-09-09 09:36 UTC, rameyer requested changes

2021-09-09 09:36 UTC, rameyer commented on interferopy/tools.py
> +    ax2.plot(bins, hist_N_fitted, drawstyle='steps-mid')
```suggestion
    ax2.plot(bins, hist_N, drawstyle='steps-mid')
    ax2.plot(bins, hist_N_fitted)
```

2021-09-09 09:37 UTC, rameyer approved these changes

2021-09-09 09:38 UTC, merged